### ISSUE TITLE
invalid issue tracker url in plugins entry

### ISSUE THREAD

**Issue by danmarsden** [nileshnpathade/moodle-enrol_payu#3]
As previously mentioned by David in CONTRIB-7148:

The issues tracker url in the plugins db needs to link here:
https://github.com/nileshnpathade/enrol_payu/issues

**Comment by nileshnpathade** [comment]
Could you please assist for how to solve this?

**Comment by nileshnpathade** [comment]
Can you please assist me for this issue?

**Comment by danmarsden** [comment]
go to:
https://moodle.org/plugins/enrol_payu

hit the "developer zone" link 

then hit the "Edit this plugin" button.

**Comment by nileshnpathade** [comment]
In my case, I have used https://tracker.moodle.org/browse/CONTRIB-7148 link for Bug tracker URL.
Am I wrong?  Please assist me.

**Comment by danmarsden** [comment]
yes that is incorrect. That is the issue "We" are using internally to track the review of your plugin. It will be closed when the review is complete.
The issues tracker in your plugin entry needs to be here in github - where I've added these issues and other people using your plugin can report issues for you to resolve.

so - it needs to be this link:
https://github.com/nileshnpathade/moodle-enrol_payu/issues

make sense now?

**Comment by nileshnpathade** [comment]
Yes, Thank You @danmarsden. Now I have replaced with link: https://github.com/nileshnpathade/moodle-enrol_payu/issues

**Comment by danmarsden** [comment]
Great - please close this to signify that you have fixed it. Thanks.
